### ISSUE TITLE
Issues when using the Arduino library with tutorial examples

### ISSUE THREAD

**Issue by BenjaminDannegard** [tensorflow/tflite-micro-arduino-examples#154]
We are updating [this tutorial](https://docs.arduino.cc/tutorials/nano-33-ble-sense/get-started-with-machine-learning) to stay accurate with the removal of the tensorflow library from the Arduino IDE, [as requested here](https://github.com/arduino/library-registry/pull/1748). We instead wanted to add a link to your github where the users could download the library, [specifically this library](https://github.com/tensorflow/tflite-micro-arduino-examples). But when we are using this library with the examples in the tutorial we are having some issues. You can find a report of the issues here: https://github.com/arduino/docs-content/pull/556#pullrequestreview-1121761235. Could you guys have a look and see if this is something you could address?

Thanks!

**Comment by ddavis-2015** [comment]
I have taken a look at your example code.  Your code will need to be modified to work with the [arduino-examples repo](https://github.com/tensorflow/tflite-micro-arduino-examples).  I suggest removing the non-compiling line of code (the include of version.h which is not needed in any way I could see).

FYI: The arduino-examples repo will continue to be updated with changes to the code base and associated APIs. This is accomplished through nightly updates from the TFLM repo.  One such API, MicroErrorReporter, and its usage has changed with respect to instantiating the MicroInterpreter.  When this update goes live, your code will again fail to compile.

This is not a TFLM issue
