### ISSUE TITLE
predict function predict(input, output) supports either int/int or float/float.?

### ISSUE THREAD

**Issue by Migue137** [tensorflow/tflite-micro-arduino-examples#155]
![204620402-fe5cd46e-cc71-4a05-bdb0-ff930ba9db5d](https://user-images.githubusercontent.com/112983796/206224548-3caffa94-6d33-4025-9e80-1e5617b2460d.png)

Hello, I was using your library and I faced up with an extrage problem, as you can see in the image 
I am using the nano 33 ble sense 

Cause my code is too big here it is the link to google drive in case you want to see it 
At frist, I thought that the problem was the EloquentTinyML library but when I opened an issue in that repository they told me that the problem it maybe be in this library.

https://drive.google.com/file/d/1nMQvWksDtZUeHM3pnOaj9i2EQ8XC2tW6/view?usp=share_link

**Comment by Migue137** [comment]
I am currently using that library but it has the same behavior as the obsolete one.
I think this repository is the best way for other users that have the same problem to see it.

I will open this issue in the Arduino Forum but, do you have any idea what is causing this error?, cause I only download the example from teachable and this error pops out.

**Comment by ddavis-2015** [comment]
The [tflite-micro-arduino-examples](https://github.com/tensorflow/tflite-micro-arduino-examples) repository has now been updated with the latest code from the tflite-micro repo.  One of the notable changes for TFLM applications is the removal of ErrorReporter, and the use of MicroPrintf() instead.  The error shown within your image appears to be related to this.

Please update your TFLM code base to that of the official repository.  Arduino examples are available within the official repository to help with any questions on the usage of TFLM APIs.
