### ISSUE TITLE
Run Arduino build process as a nightly CI action

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tflite-micro-arduino-examples#23]
This repository doesn't have any automated Arduino build checking. The source repo at https://github.com/tensorflow/tflite-micro does however, so I think it would be useful to port those scripts over here.

**Comment by advaitjain** [comment]
We have nightly and nightly and per PR checks: https://github.com/tensorflow/tflite-micro-arduino-examples/blob/main/.github/workflows/ci.yml

And the build badge from tflite-micro points to the nightly build from this repository.
