### ISSUE TITLE
Missing script for end-to-end repo tree creation

### ISSUE THREAD

**Issue by ddavis-2015** [tensorflow/tflite-micro-arduino-examples#6]
@tensorflow/micro 

Need to add script that does full TFLM Arduino tree creation and build test.

**Comment by njeffrie** [comment]
Does tensorflow/lite/micro/tools/ci_build/test_arduino.sh work for you, or is something missing?

**Comment by ddavis-2015** [comment]
I have run the test_arduino.sh script against the tflite-micro repo.  No issues were found.
